#%RAML 1.0
title: Fabonacci webservice.
description: A sample web service for vitustream interview.
version: v0.0.0.1
mediaType: application/json

/fibonacci:
  get:
    queryParameters:
      numbers:
        displayName: fibnacci number.
        type: number
        example: 4
        required: true
  responses:
    200:
      description: Fabonacci list
      headers:
        Content-Type:
          default: application/json;charset=UTF-8
      body:
        application/json:
          type: |
                {
                  "$schema": "http://json-schema.org/draft-04/schema#",
                  "type": "object",
                  "properties": {
                    "Data": {
                      "type": "string"
                    },
                  },
                }
              example: |
                {
                  "result": "[1,1,2,3]"
                }
      400:
        description: Request parameters invalid.
        body:
          example: "invalid number"

      500:
        description: Internal server error.
        body:
          example: "internal_server_error"
