#%RAML 1.0
title: Fabonacci webservice API.
description: A sample web service for demo.
version: v1


/fibonacci:
  get:
    description: Get a list of fibonacci numbers
    queryParameters:
      numbers:
        description: Specify the numbers you want to get
        type: integer
        example: 4
        required: true
    responses:
      200:
         description: Fabonacci list
         headers:
           Content-Type:
            default: application/json;charset=UTF-8
         body:
           application/json:
            example: |
              {
                "Data": "[1,1,2,3]"
              }
      400:
         description: Invalid query parameters.
         body:
           plain/text:
            example: "invalid numbers"
      404:
         description: Page not found.
         body:
           plain/text:
            example: "page not found"
      500:
         description: Internal server error.
         body:
           plain/text:
            example: "internal_server_error"

/heartbeat:
   get:
    description: heartbeat API
    responses:
     200:
       body:
         plain/text:
          example: "I am alive"
